module.exports = {
  // 趣备课
  Interesting: {
    // 首页
    home: {
      page_title: "首页",
      index_title1: "备上课总览",
      index_title2: "我的课程表",
      index_title3: "近两周备课提醒",
      filterTabs: ["本周", "本月", "高级筛选"],
      filterStatusTabs: ["待备课", "备课延迟"],
      remindBtns: ["备课", "我知道啦"],
      classScheduleStaus: ["已备课/已上课", "待备课/待上课"],
      weeks: ["周日", "周一", "周二", "周三", "周四", "周五", "周六"],
      classSchedulePover: {
        status1: "已备课",
        status2: "已上课",
        status1_2: "待备课",
        status2_2: "待上课",
        class_name: "班级名称",
        course_name: "课程别",
        class_room: "上课教室",
        time: "上课时间",
        btn_name: "备课",
      },
      remind_text1: "班级",
      placeholder1: "请选择班级",
    },
    // 备课提醒
    classReminder: {
      page_title: "备课提醒",
      remkRead_cont: "确定将已选中提醒标记为已读吗？",
      allRead_cont: "确定将全部提醒标记为已读吗？",
      btn_text1: "全部已读",
      btn_text2: "标记已读",
      btn_text3: "备课",
      filter_name1: "日期",
      placeholder1: ["至", "开始日期", "结束日期"],
      filter_name2: "班级",
      placeholder2: "选择班级",
      filter_name3: "课程",
      placeholder3: "选择课程",
      filter_name4: "阅读状态",
      placeholder4: "选择阅读状态",
      readStatus: ["已阅读", "未阅读"],
    },
    // 备课
    prepareLessons: {
      page_title: "我的班级",
      btn_text1: "备课",
      filter_name1: "校园",
      placeholder1: "选择校园",
      filter_name2: "课程别",
      placeholder2: "选择课程别",
      filter_name3: "教师",
      placeholder3: "选择教师",
      filter_name4: "教室",
      placeholder4: "选择教室",
      placeholder5: "请输入班级名称",
      filterTabs: ["卡片模式", "列表模式"],
      status: ["进行中", "未开始"],
      labe_text1: "上次备课时间:",
      labe_text2: "课程别：",
      labe_text3: "教室：",
      labe_text4: "课程别编号：",
      labe_text5: "校园：",
      labe_text6: "人数：",
      canvas_text1: ["上课总进度", "上课进度", "上课完成进度"],
      canvas_text2: ["备课总进度", "备课进度", "备课完成进度"],
      slider_title: "选择课时",
    },
    // 单个班级备课
    preLessonDetais: {
      filterTabs: ["教案模式", "视频模式"],
      topInfoList: ["班级名称：", "教师名称：", "上课时间："],
      btn_text1: "预览批注",
      btn_text2: "打印批注",
      btn_text3: "标记重难点",
      btn_text4: "取消重难点",
      btn_text5: "标记不讲",
      btn_text6: "取消不讲",
      btn_text7: "上传我的教学视频",
      small_title1: "个人备注",
      small_title2: "教学教案",
      small_title3: "教学视频",
      small_title4: "教学中心批注",
      small_title5: "优质批注推荐",
      small_title6: "点击查看优质批注内容",
      small_title7: "优秀教学视频分享",
      small_title8: "点击查看优秀教学视频",
      small_title9: "教学注意事项",
      placeholder1: "老师您可以在这里添加教学辅助内容",
      courseFile: ["OFFICE档案", "影音档案", "图档"],
      seeFile: "查看文件",
      high_work: "优秀教学作品推荐",
      see_more: "查看更多",
      allwork_placeholder: "请输入老师姓名",
      sortList: ["综合排序", "点赞数", "观看数", "最新上架"],

      highRecommend_title: "优质推荐内容",
      highRecommend_stitle1: "热门批注",
      highRecommend_stitle2: "优质批注",
      highVideo_stitle1: "优秀教学视频",
      highVideo_stitle2: "其他优秀教学作品",
      showText: ["展开内容", "收起内容"],
      bottomText: ["来自", "观看", "点赞"],
    },
    // 报表
    report: {
      page_title: "报表",
      btn_text1: "导出",
      btn_text2: "教师统计",
      btn_text3: "班级课时统计",
      filter_name1: "日期",
      placeholder1: "选择日期",
      filter_name2: "校园",
      placeholder2: "选择校园",
      placeholder3: "请输入班级名称/班级编号",
      classReport: {
        page_title: "班级统计",
        page_title1: "班级备课详情",
        countInfo: ["教师姓名", "教师编号", "校园名称", "带课班级数"],
        filter_name1: "课程别",
        placeholder1: "选择课程别",
        filter_name2: "备课状态",
        placeholder2: "选择备课状态",
        filter_name3: "上课状态",
        placeholder3: "选择上课状态",
        filter_name4: "班级名称",
        placeholder5: "选择班级名称",
        placeholder4: "请输入班级名称/班级编号",
      },
    },
  },
  // 培训
  Training: {
    // 首页
    home: {
      page_title: "职业成长",
      page_title_right: "培训>",
      page_title_right2: "职业成长",
      index_title1: "教学成长路线",
      learningProgress: [
        "保教实习生",
        "保教组长",
        "保教主任",
        "保教组长",
        "保教组长",
        "保教组长",
      ],
    },
    progressCard: {
      progressItem: ["第一阶段", "第二阶段", "第三阶段"],
      progressTitle: ["恭喜你", "学习中", "待学习"],
      study: "立即学习",
      exam: "考核",
      viewClass: "查看课程",
    },
    LearningOnce: {
      LearningOnce:
        "温馨提示:按照您的职务为您自动规划职务成长路线,请按照指示引导依次完成各阶段的学习,促进教师的专业成长~",
    },
    LearningStages: {
      infoTitle: ["职务名称", "学习阶段", "学习完成进度", "考核完成进度"],
      learnProgress: "学习阶段列表",
      scoped: ["查看，考核"],
    },
    Assessment: {
      info: [
        "第一阶段考核",
        "考核时长：",
        "考核题数：",
        "开始考核",
        "分钟",
        "道题",
      ],
      infoNext: ["上次分数:", "80分", "上次用时:", "12分钟"],
    },
    AssessProgress: {
      info: ["考核", "考核记录"],
    },
    InExam: {
      title: "第一阶段考核",
      progress: ["完成进度", "待完成", "倒计时：", "提交", "已完成"],
      popinfo: [
        "立即提交",
        "暂不提交",
        "提示",
        "考核时间已到，是否立即提交？",
        "是否立即提交?",
      ],
    },
    ExaminationRecord: {
      scoped: ["查看答案", "暂无答案"],
    },
    Answer: {
      info: [
        "查看答案",
        "只看错题",
        "考核分数",
        "共有错题：",
        "分",
        "道",
        "查看全部",
      ],
      answer: ["【正确答案】:", "您的答案是：", "【解析】", "统计"],
    },
    ViewCourses: {
      info: [
        "查看课程",
        "培训>职业成长>",
        "课程介绍",
        "第一阶段",
        "教学评比优秀课程",
        "人已学",
        "收藏",
        "课程资料预览",
      ],
      info2: [
        "考试、作业、练习区别如下：",
        "考试比作业、练习多了考试时间和考试次数设置，可以设置定时考试；",
        "考试需要批阅，作业需要批改，练习无批阅；",
        "考试结果有分数成绩，作业、练习无成绩分数；",
        "考试、作业有结果记录和数据分析，练习无数据记录；",
        "考试、作业发布后题目固定，练习题目不固定，可能每次练习题目和顺序都不相同。",
      ],
      title: "课程目录",
      coninfo: ["音频", "视频", "图片"],
      learning: "正在学习",
    },
    Watch: {
      info: [
        "观看课程",
        "培训>职业成长>",
        "查看我的全部笔记",
        "请输入笔记内容",
        "上一节",
        "下一节",
      ],
      save: "保存",
      edit: "编辑",
    },
    OpenClass: {
      info: ["通识课", "全部课件", "学科通识课", "校长培训"],
    },
    AllCourseware: {
      info: ["最新", "最热", "推荐"],
      tips:
        "温馨提示：开放通识课旨在为教师带来更好的教育指导以及好的教学方法，快快学习吧～",
      tipsBlank:'暂无课程哦~'
    },
    Card: {
      info: ["人已学", "课程简介:"],
    },
    form: {
      info: [
        "职务统计培训报表",
        "职务统计通识课报表",
        "教师统计报表",
        "通识课统计报表",
      ],
    },
    TrainingReport: {
      info: [
        "职务名称:",
        "教师统计",
        "培训>",
        "职业统计培训报表",
        "导出",
        "请输入教师姓名/编号",
      ],
      form2: "职务统计通识课报表",
      form3: "教师统计报表",
      form4: "通识课统计报表",
    },
  },
  // 教务管理
  Educational: {
    // 小循环登记
    circulateRegistrat: {
      title: "我的班级",
      my_class: "我的班级",
      class_tab: ["进行中", "未开始", "全部"],
      circle_tab: ["课时登记", "电访管理"],
      choose_class: "请选择课时：",
      school: "校园",
      school_ph: "请选择校园",
      course: "课程别",
      course_ph: "请选择课程别",
      teacher: "教师",
      teacher_ph: "请选择教师",
      classroom: "教室",
      classroom_ph: "请选择教室",
      classstatus: "班级状态",
      classstatus_ph: "请选择班级状态",
      statusList: ["待开班", "进行中", "已结束"],
      find_ph: "请输入班级名称/班级编号",
      tip1: "铃铛代表延迟",
      tip2: "个及以上课次未登记教务工作",
      tip3: "闹钟代表延迟",
      tip4: "个课次未登记教务工作",
      pro: "上课进度: ",
      pro1: "个课次未登记",
      table_option: {
        title: "功能操作",
        content: ["线下登记", "网课参与", "补课记录", "电访管理"],
      },
      offlineRegist: {
        find_ph: "请输入学员中英文名/学员编号",
        placehold: "请选择小书检核状态",
        select: ["已完成", "未完成"],
      },
      onlineclass: {
        placehold: "请选择参与状态",
        select: ["已参与", "未参与", "待参与"],
      },
      missclassRecord: {
        placehold: "请选择补课状态",
        select: ["无补课", "已补课", "未补课"],
      },
      callManagement: {
        addCall: "添加电访",
        callRecord: "电访记录",
        name: "姓名",
        count: "已沟通次数",
        time: "上次沟通时间",
        tim: "沟通时间",
        none: "不限",
        mode: "查看沟通模版",
        form: {
          commun_type: "沟通类型",
          commun_type_ph: "请选择沟通类型",
          commun_name: "沟通对象",
          commun_name_ph: "请选择沟通对象",
          commun_time: "沟通日期",
          commun_time_ph: "请选择沟通日期",
          commun_result: "沟通结果",
          commun_result_ph: "请选择沟通结果",
          commun_result_arr: ["无效沟通", "有效沟通"],
          commun_content: "沟通内容",
          commun_content_ph: "请输入沟通内容",
          commun_nexttime: "下次跟进日期",
          commun_nexttime_ph: "请选择下次跟进日期",
          red_tip: "*为必填字段",
        },
        call_time: "电访日期",
        range: "至",
        start_time: "开始日期",
        end_time: "结束日期",
        find_ph: "请输入姓名/学号",
        find_ph1: "请输入学员中文名、英文名、学员编号",
        a1: "查看电访",
        a2: "学员中文名",
        a3: "学员英文名",
        a4: "学员编号",
        a5: "本次电访状态",
        a6: "上次电访时间",
        a7: "添加电访记录",
        a8: "查看电访记录",
        a9: "查看本次电访话术",
        a10: "电访状态",
        a11: "请选择电访状态",
      },
      a1: "一键已参与",
      a2: "一键无补课",
      a3: "一键已完成",
    },
    // 教务检核状况
    checkStatusrouter: {
      title: "教务核检状况",
      handsee: "查看",
      viewCheckStatus: "查看核检状况",
      viewCheckDetails: "查看教务核检详情",
      classTeaching: {
        online: "线上",
        offline: "线下",
        homework_finish: "作业完成率",
        record_course: "录播课程",
        course_watch: "录播课程观看状况 (次数)",
        online_score: "线上检测分数",
        dub_rate: "配音达标率",
        teacher_word: "老师评语",
        parent_word: "家长反馈",
        parent_servey: "家长满意度调查函",
        parent_inquiry: "家长满意度调查",
        offline_test: "线下考试成绩",
        offline_homework: "线下作业分数",
        book_check: "小书检核",
        course_take: "网课参与",
        course_score: "网课检测分数",
        lesson_record: "补课记录",
        ci: "次",
      },
    },
    // 报表
    educationalReport: {
      title1: "班级教师统计报表",
      title2: "中心基地报表",
      title3: "教务工作报表",
      classReport: {
        campus: "校园",
        campus_ph: "请选择校园",
        class: "课程别",
        class_ph: "请选择课程别",
        find_ph: "请输入班级名称/班级编号",
        find_ph1: "请输入班级中英文名、班级编号",
        classTime: "课时统计",
        callRecord: "电访记录",
        findDetail: "查看明细",
      },
      teacherReport: {
        campus: "校园",
        campus_ph: "请选择校园",
        find_ph: "请输入教师名称/教师编号",
        roomCount: "班级统计",
      },
      schoolTaskReport: {
        a1: "选择时间",
        a2: "组织架构模式",
        a3: "请选择组织架构模式",
        a4: "组织架构",
        a5: "二级架构",
        a6: "三级架构",
        a7: "查看校总表",
        a8: "校总表",
        find_ph: "请输入学校名称搜索",
      },
      classTaskReport: {
        find_ph: "请输入班级中英文名",
      },
      classTime: {
        class_name: "班级名称",
        school_name: "校园名称",
        class_progress: "课时进度",
        class_info: "课时信息",
        class: "课时",
        class_ph: "请选择课时",
        student_info: "学生检核状况",
        find_ph: "请输入学员中英文姓名/学员编号",
      },
      callRecord: {
        student_list: "学生列表",
        call_time: "电访日期",
        range: "至",
        start_time: "开始日期",
        end_time: "结束日期",
        find_ph: "请输入学员中英文姓名/学员编号",
      },
      eduWorkDetail: {
        a1: "班级中文名",
        a2: "班级英文名",
        a3: "班级编号",
        a4: "主教老师",
        a5: "助教老师",
        a6: "应上/总课次数",
        a7: "实际登记课次数",
        a8: "未登记课次数",
        a9: "上课状态",
        a10: "请选择上课状态",
        a11: "登记状态",
        a12: "请选择登记状态",
        a13: "请输入课次名称",
        a14: ["已考勤", "待考勤", "待上课"],
        a15: ["已登记", "未登记"],
      },
    },
    // 课表
    MySchedule: {
      page_title: "我的课表",
    },
    // 叮铛助教
    JingleAssistant: {
      timeListText: [
        "不限",
        "今日",
        "昨日",
        "本周",
        "近7天",
        "近30天",
        "本月",
        "上月",
      ],
      // 教务工作
      educationWork: {
        page_title: "教务工作",
        innerSliderArr: ["上课点评", "发布作业", "沟通管理", "通知管理"],
        labe1: "班",
        labe2: "课程别名称",
        labe3: "课程别编号",
        labe4: "校园",
        labe5: "教师",
        labe6: "教室",
        labe7: "人数",
        // 上课点评
        child1: {
          labe1: "请选择课时",
          labe2: "上课内容",
          labe3: "添加上课内容",
          labe4: "点评状态：",
          labe5: "已选中",
          labe6: "个学员",
          btn_text1: "查看",
          btn_text2: "重新编辑",
          btn_text3: "点评",
          btn_text4: "撤销点评",
          btn_text5: "清空",
          btn_text6: "保存草稿",
          btn_text7: "提交",
          btn_text8: "上传图片",
          btn_text9: "选择评价模版",
          labe7: "已选择",
          labe10: "人",
          placeholder1: "请输入上课内容",
          placeholder2: "请输入对学生的评价",
          title1: "批量点评",
          title2: "点评",
          title3: "查看点评",
          title4: "编辑点评",
          title5: "选择点评模板",
          labe8: "共",
          labe9: "条评价",
          TabList: ["全部", "已评", "未评"],
          popTipsRevoke: "撤销点评后，家长将不收到此点评内容，确定撤销点评？",
          imgTips1: "上传头像图片只能是 JPG/PNG/GIF 格式!",
          imgTips2: "上传头像图片大小不能超过 2MB!",
        },
        // 发布作业
        child2: {
          aa: "发布作业",
          ab: "已发布作业",
          ac: "作业已发布成功",
          ad: "继续发布",
          ae: "清空",
          af: "发送",
          ag: "请选择课时",
          ah: "接收人",
          ai: "接收人数",
          aj: "添加学生",
          ak: "标题",
          al: "请输入标题",
          am: "内容",
          an: "共",
          ao: "人未添加",
          ap: "请输入作业标题",
          aq: "请输入作业内容",
          ar: "查看",
          as: "待上课的课时暂时不能发布作业哦~ ",
        },
        // 沟通管理
        child3: {
          aa: "请输入姓名、编号",
          ab: "添加沟通",
          ac: "沟通记录",
          ad: "选择沟通模版",
        },
        // 通知管理
        child4: {
          aa: "发布通知",
          ab: "通知列表",
          ac: "通知发布成功",
          ad: "请输入通知标题",
          ae: "请输入通知内容",
          af: "发布时间",
          ag: "请选择时间范围",
          ah: "查看",
          ai: "查看阅读状态",
        },
      },
      // 作业管理
      homeWork: {
        page_title: "作业管理",
        innerSliderArr: ["作业查询", "作业统计"],
        labe_text1: "时间范围",
        placeholder1: "请选择时间范围",
        labe_text11: "学校",
        placeholder11: "请选择学校",
        labe_text2: "班级",
        placeholder2: "请选择班级",
        labe_text3: "老师",
        placeholder3: "请选择老师",
        placeholder4: "标题",
        labe_text4: "发送人：",
        labe_text5: "上课时间：",
        labe_text6: "接收人",
        labe_text7: "阅读状态",
        placeholder5: "请选择时间范围",
        placeholder6: "班级名称",
        placeholder7: "老师名称",
        title1: "作业详情",
        title2: "查看作业完成状态",
        tips:
          "1、作业数表示发布作业数量；2、发送人数表示已发送作业的学员数量；3、阅读人数表示已阅读作业的学员数量；4、提交人数表示已提交的学员数量；5、评价人数表示老师评价的学员数量",
        tabs: ["已读", "未读", "已交", "已评", "全部"],
        pageTabs: ["按班级", "按老师"],
        blankTips: [
          "暂无已读作业",
          "暂无未读作业",
          "暂无已交作业",
          "暂无已评作业",
          "暂无全部作业",
        ],
      },
      // 通知管理
      noticeManage: {
        page_title: "通知管理",
        innerSliderArr: ["通知管理", "公告管理"],
        labe_text1: "时间范围",
        placeholder1: "请选择时间范围",
        labe_text2: "班级",
        placeholder2: "请选择班级",
        labe_text3: "老师",
        placeholder3: "请选择老师",
        placeholder4: "标题",
        labe_text4: "发送人：",
        labe_text5: "已读人数：",
        title1: "通知详情",
        title2: "查看通知完成状态",
        title3: "公告详情",
        title4: "发布通告",
        title5: "编辑公告",
        btn_text1: "发布公告",
        btn_text2: "发布",
        btn_text3: "编辑",
        tips: "接收人为我校学员",
        tabs: ["已读", "未读", "全部"],
        status: ["已读", "未读"],
        form_text1: "公告标题：",
        form_text100: "所属学校：",
        form_text2: "公告内容：",
        form_rule1: "请输入公告标题",
        form_rule2: "请输入公告内容",
        blankTips: ["暂无已读通知", "暂无未读通知", "暂无全部通知"],
      },
      // 家长评价老师
      parentAssess: {
        aa: "按老师",
        ab: "按老师+班级",
        ac: "家长评价老师",
        ad: "评价查询",
        ae: "老师得分统计",
        af: "时间范围",
        ag: "选择时间",
        ah: "选择日期",
        ai: "班级",
        aj: "选择班级",
        ak: "老师",
        al: "选择老师",
        am: "学员中英文名、学员编号、联系电话",
        an: "出勤学员评价详情",
        ao: "是否评价",
        ap: "请输入学员中英文名、学员编号",
        aq: "否",
        ar: "是",
      },
      // 投诉与建议
      complaint: {
        page_title: "投诉与建议",
        innerSliderArr: ["学校", "老师"],
        labe_text1: "时间范围",
        placeholder1: "请选择时间范围",
        labe_text2: "选择日期",
        placeholder2: "学员中英文名、学员编号、联系电话",
        title1: "投诉与建议",
        labe_text3: "时间",
        labe_text4: "对象",
      },
    },
  },
  // 个人中心
  myCenter: {
    page_myClass_title: "我的班级",
    page_currentCourse_title: "在学课程",
    page_myComment_title: "我的批注",
    page_myCollect_title: "我的收藏",
    page_myVideo_title: "我的教学视频",
    page_myNote_title: "我的笔记",
    video_mark: "优秀教学视频",
    placeholder1: "请输入班级名称、课程别名称、课程别编号",
    placeholder2: "请输入课程名称",
    placeholder3: "请输入课时名称",
    placeholder4: "请选择审核类型",
    placeholder5: "请输入内容",
    tips_title: " 温馨提示：",
    tips_cont1:
      "上传您的教学视频后将由教学中心审核，教学中心审核通过后将有机会将您的教学视频推荐为优秀教学视频供老师们查看哦～",
    tips_cont2: "审核拒绝后您可重新上传 新的教学视频～",
    labe_text1: "进行中",
    labe_text2: "未开始",
    labe_text3: "课程别：",
    labe_text4: "课程别编号：",
    labe_text5: "校园：",
    labe_text6: "人数：",
    labe_text7: "完成度",
    labe_text8: "审核类型",
    labe_text9: "上传日期：",
    labe_text10: "人已学",
    video_status: ["待审核", "审核通过", "审核驳回"],
  },
  // 消息中心
  myMessage: {
    btn_text1: "标记已读",
    page_messageDetail_title: "消息详情",
  },
  // 个人设置
  mySettings: {
    page_myinfo_title: "个人信息",
    page_accoutInfo_title: "账号信息",
    page_common_title: "基本信息",
    page_staff_title: "职务信息",
    head_photo: "头像",
    img_text: [
      "将图片拖到此处，或",
      "点击上传",
      "仅限jpeg，png格式，图片大小不超过2M",
    ],
    page_info: {
      teacher_cname: "教师中文名",
      teacher_ename: "教师英文名",
      gender: "性别",
      man: "男",
      women: "女",
      date: "出生日期",
      staff_name: "职务名称",
      job: "角色",
      staff_leavel: "职等",
      account: "账号",
      password: "修改密码",
      number: "手机号",
      email: "邮箱",
      changepassword: "修改密码",
    },
    password_dialog: {
      titie: "修改密码",
      newpass: "请输入新密码",
      newpass_ph: "请输入六位数字新密码",
      confirmpass: "请确认密码",
      confirmpass_ph: "请再次确认密码",
      confirm: "确认",
      cancel: "取消",
    },
  },
  // 公共部分
  Common: {
    header: {
      nav_name1: "趣备课",
      nav_name2: "培训",
      nav_name3: "教务管理",
      languageTab: "切换语言",
      userOperate1: "个人中心",
      userOperate2: "个人设置",
      userOperate3: "退出登录",
      changeSchoolTitle: "请选择您要进入的学校",
      schoolTab: "切换",
      changeSchool: {
        placeholder1: "选择区域",
        placeholder2: "选择省",
        placeholder3: "选择市",
        placeholder4: "请输入校园编号,校园名称",
      },
    },
    mode: {
      card_mode: "卡片模式",
      list_mode: "列表模式",
    },
    collect_text: "收藏",
    video_tips: "您的浏览器不支持 video 标签",
    page: ["第", "页"],
    pop_title: "提示",
    noread_text: "未读",
    btn_save: "保存",
    btn_edit: "修改",
    btn_del: "删除",
    btn_edit2: "编辑",
    btn_sure: "确定",
    btn_cancel: "取消",
    log_out_cont: "确定退出当前帐号？",
    input_button: "查询",
    input_submit: "提交",
    btn_see_comment: "查看批注",
    export: "导出",
    export_tips: "没有可导出的数据哦",
    print: "打印",
    preview: "预览",
    see: "查看",
    piece: "个",
    download: "下载",
    start_time: "开始日期",
    end_time: "结束日期",
    range_time: "至",
    man: "男",
    woman: "女",
    popTips: "提示",
    popTips_del: "是否确定删除？",
    table_operate: "操作",
    audioTips: "您的浏览器不支持 audio 标签。",
    videoTips: "您的浏览器不支持 video 标签。",
    back: "返回",
  },
  // 组件-----------start
  // 表格
  Table: {
    a1: "啊哦～暂时没有内容哦",
    a2: "编辑列",
    a3: "已显示列",
    a4: "未显示列",
    a5: "确定",
    a6: "提示",
  },
  // 课表
  mySchedule: {
    tabsList: ["日视图", "周视图", "月视图"],
    statusArr: ["待考勤", "已考勤"],
    placeholder1: "选择日期",
    placeholder2: "选择月",
    text: "至",
    labe_text1: "时间：",
    labe_text2: "班级别名：",
    labe_text3: "课程别：",
    labe_text4: "校区：",
    labe_text5: " 教室：",
    labe_text6: "状态：",
    emptyTip: "课表暂无数据",
    weekdayArr: ["周日", "周一", "周二", "周三", "周四", "周五", "周六"],
  },
  // 组件-----------end
  // 路由部分
  storeRouter: {
    Slider1: ["首页", "备课", "报表"],
    Slider2: ["职业成长", "通识课", "报表"],
    Slider3: [
      "首页",
      "我的课表",
      "小循环登记",
      "教务检核状况",
      "叮铛助教",
      "教务工作",
      "消息查询",
      "作业管理",
      "通知管理",
      "老师评价学生",
      "家长评价老师",
      "投诉与建议",
      "报表",
    ],
    Slider4: [
      "我的班级",
      "在学课程",
      "我的批注",
      "我的笔记",
      "我的教学视频",
      "我的收藏",
    ],
    Slider5: ["个人信息", "账号信息"],
  },
};
