module.exports = {
  // 趣備課
  Interesting: {
    // 首頁
    home: {
      page_title: "首頁",
      index_title1: "備上課總覽",
      index_title2: "我的課程表",
      index_title3: "近兩周備課提醒",
      filterTabs: ["本周", "本月", "高級篩選"],
      filterStatusTabs: ["待備課", "備課延遲"],
      remindBtns: ["備課", "我知道啦"],
      classScheduleStaus: ["已備課/已上課", "待備課/待上課"],
      weeks: ["周日", "周一", "周二", "周三", "周四", "周五", "周六"],
      classSchedulePover: {
        status1: "已備課",
        status2: "已上課",
        status1_2: "待備課",
        status2_2: "待上課",
        class_name: "班級名稱",
        course_name: "課程別",
        class_room: "上課教室",
        time: "上課時間",
        btn_name: "備課",
      },
      remind_text1: "班級",
      placeholder1: "請選擇班級",
    },
    // 備課提醒
    classReminder: {
      page_title: "備課提醒",
      remkRead_cont: "確定將已選中提醒標記為已讀嗎？",
      allRead_cont: "確定將全部提醒標記為已讀嗎？",
      btn_text1: "全部已讀",
      btn_text2: "標記已讀",
      btn_text3: "備課",
      filter_name1: "日期",
      placeholder1: ["至", "開始日期", "結束日期"],
      filter_name2: "班級",
      placeholder2: "選擇班級",
      filter_name3: "課程",
      placeholder3: "選擇課程",
      filter_name4: "閱讀狀態",
      placeholder4: "選擇閱讀狀態",
      readStatus: ["已閱讀", "未閱讀"],
    },
    // 備課
    prepareLessons: {
      page_title: "我的班級",
      btn_text1: "備課",
      filter_name1: "校園",
      placeholder1: "選擇校園",
      filter_name2: "課程別",
      placeholder2: "選擇課程別",
      filter_name3: "教師",
      placeholder3: "選擇教師",
      filter_name4: "教室",
      placeholder4: "選擇教室",
      placeholder5: "請輸入班級名稱",
      filterTabs: ["卡片模式", "列表模式"],
      status: ["進行中", "未開始"],
      labe_text1: "上次備課時間:",
      labe_text2: "課程別：",
      labe_text3: "教室：",
      labe_text4: "課程別編號：",
      labe_text5: "校園：",
      labe_text6: "人數：",
      canvas_text1: ["上課總進度", "上課進度", "備課完成進度"],
      canvas_text2: ["備課總進度", "備課進度", "上課完成進度"],
      slider_title: "選擇課時",
    },
    // 單個班級備課
    preLessonDetais: {
      filterTabs: ["教案模式", "視頻模式"],
      topInfoList: ["班級名稱：", "教師名稱：", "上課時間："],
      btn_text1: "預覽批註",
      btn_text2: "打印批註",
      btn_text3: "標記重難點",
      btn_text4: "取消重難點",
      btn_text5: "標記不講",
      btn_text6: "取消不講",
      btn_text7: "上傳我的教學視頻",
      small_title1: "個人備註",
      small_title2: "教學教案",
      small_title3: "教學視頻",
      small_title4: "教學中心批註",
      small_title5: "優質批註推薦",
      small_title6: "點擊查看優質批註內容",
      small_title7: "優秀教學視頻分享",
      small_title8: "點擊查看優秀教學視頻",
      small_title9: "教學註意事項",
      placeholder1: "老師您可以在這裏添加教學輔助內容",
      courseFile: ["OFFICE檔案", "影音檔案", "圖檔"],
      seeFile: "查看文件",
      high_work: "優秀教學作品推薦",
      see_more: "查看更多",
      allwork_placeholder: "請輸入老師姓名",
      sortList: ["綜合排序", "點贊數", "觀看數", "最新上架"],

      highRecommend_title: "優質推薦內容",
      highRecommend_stitle1: "熱門批註",
      highRecommend_stitle2: "優質批註",
      highVideo_stitle1: "優秀教學視頻",
      highVideo_stitle2: "其他優秀教學作品",
      showText: ["展開內容", "收起內容"],
      bottomText: ["來自", "觀看", "點贊"],
    },
    // 報表
    report: {
      page_title: "報表",
      btn_text1: "導出",
      btn_text2: "教師統計",
      btn_text3: "班級課時統計",
      filter_name1: "日期",
      placeholder1: "選擇日期",
      filter_name2: "校園",
      placeholder2: "選擇校園",
      placeholder3: "請輸入班級名稱/班級編號",
      classReport: {
        page_title: "班級統計",
        page_title1: "班級備課詳情",
        countInfo: ["教師姓名", "教師編號", "校園名稱", "帶課班級數"],
        filter_name1: "課程別",
        placeholder1: "選擇課程別",
        filter_name2: "備課狀態",
        placeholder2: "選擇備課狀態",
        filter_name3: "上課狀態",
        placeholder3: "選擇上課狀態",
        filter_name4: "班級名稱",
        placeholder5: "選擇班級名稱",
        placeholder4: "請輸入班級名稱/班級編號",
      },
    },
  },
  // 培訓
  Training: {
    // 首頁
    home: {
      page_title: "職業成長",
      page_title_right: "培訓>",
      page_title_right2: "職業成長",
      index_title1: "教學成長路線",
      learningProgress: [
        "保教實習生",
        "保教組長",
        "保教主任",
        "保教組長",
        "保教組長",
        "保教組長",
      ],
    },
    progressCard: {
      progressItem: ["第一階段", "第二階段", "第三階段"],
      progressTitle: ["恭喜妳", "學習中", "待學習"],
      study: "立即學習",
      exam: "考核",
      viewClass: "查看課程",
    },
    LearningOnce: {
      LearningOnce:
        "溫馨提示:按照您的職務為您自動規劃職務成長路線,請按照指示引導依次完成各階段的學習,促進教師的專業成長~",
    },
    LearningStages: {
      infoTitle: ["職務名稱", "學習階段", "學習完成進度", "考核完成進度"],
      learnProgress: "學習階段列表",
      scoped: ["查看，考核"],
    },
    Assessment: {
      info: [
        "第一階段考核",
        "考核時長：",
        "考核題數：",
        "開始考核",
        "分鐘",
        "道題",
      ],
      infoNext: ["上次分數:", "80分", "上次用時:", "12分鐘"],
    },
    AssessProgress: {
      info: ["考核", "考核記錄"],
    },
    InExam: {
      title: "第一階段考核",
      progress: ["完成進度", "待完成", "倒計時：", "提交", "已完成"],
      popinfo: [
        "立即提交",
        "暫不提交",
        "提示",
        "考核時間已到，是否立即提交？",
        "是否立即提交?",
      ],
    },
    ExaminationRecord: {
      scoped: ["查看答案", "暫無答案"],
    },
    Answer: {
      info: [
        "查看答案",
        "只看錯題",
        "考核分數",
        "共有錯題：",
        "分",
        "道",
        "查看全部",
      ],
      answer: ["【正確答案】:", "您的答案是：", "【解析】", "統計"],
    },
    ViewCourses: {
      info: [
        "查看課程",
        "培訓>職業成長>",
        "課程介紹",
        "第一階段",
        "教學評比優秀課程",
        "人已學",
        "收藏",
        "課程資料預覽",
      ],
      info2: [
        "考試、作業、練習區別如下：",
        "考試比作業、練習多了考試時間和考試次數設置，可以設置定時考試；",
        "考試需要批閱，作業需要批改，練習無批閱；",
        "考試結果有分數成績，作業、練習無成績分數；",
        "考試、作業有結果記錄和數據分析，練習無數據記錄；",
        "考試、作業發布後題目固定，練習題目不固定，可能每次練習題目和順序都不相同。",
      ],
      title: "課程目錄",
      coninfo: ["音頻", "視頻", "圖片"],
      learning: "正在學習",
    },
    Watch: {
      info: [
        "觀看課程",
        "培訓>職業成長>",
        "查看我的全部筆記",
        "請輸入筆記內容",
        "上一節",
        "下一節",
      ],
      save: "保存",
      edit: "編輯",
    },
    OpenClass: {
      info: ["通識課", "全部課件", "學科通識課", "校長培訓"],
    },
    AllCourseware: {
      info: ["最新", "最熱", "推薦"],
      tips:
        "溫馨提示：開放通識課旨在為教師帶來更好的教育指導以及好的教學方法，快快學習吧～",
      tipsBlank:'暫無課程哦~'
    },
    Card: {
      info: ["人已學", "課程簡介:"],
    },
    form: {
      info: [
        "職務統計培訓報表",
        "職務統計通識課報表",
        "教師統計報表",
        "通識課統計報表",
      ],
    },
    TrainingReport: {
      info: [
        "職務名稱:",
        "教師統計",
        "培訓>",
        "職業統計培訓報表",
        "導出",
        "請輸入教師姓名/編號",
      ],
      form2: "職務統計通識課報表",
      form3: "教師統計報表",
      form4: "通識課統計報表",
    },
  },
  // 教務管理
  Educational: {
    // 小循環登記
    circulateRegistrat: {
      title: "我的班級",
      my_class: "我的班級",
      class_tab: ["進行中", "未開始", "全部"],
      circle_tab: ["課時登記", "電訪管理"],
      choose_class: "請選擇課時：",
      school: "校園",
      school_ph: "請選擇校園",
      course: "課程別",
      course_ph: "請選擇課程別",
      teacher: "教師",
      teacher_ph: "請選擇教師",
      classroom: "教室",
      classroom_ph: "請選擇教室",
      classstatus: "班級狀態",
      classstatus_ph: "請選擇班級狀態",
      statusList: ["待開班", "進行中", "已結束"],
      find_ph: "請輸入班級名稱/班級編號",
      tip1: "鈴鐺代表延遲",
      tip2: "個及以上課次未登記教務工作",
      tip3: "鬧鐘代表延遲",
      tip4: "個課次未登記教務工作",
      pro: "上課進度: ",
      pro1: "個課次未登記",
      table_option: {
        title: "功能操作",
        content: ["線下登記", "網課參與", "補課記錄", "電訪管理"],
      },
      offlineRegist: {
        find_ph: "請輸入學員中英文名/學員編號",
        placehold: "請選擇小書檢核狀態",
        select: ["已完成", "未完成"],
      },
      onlineclass: {
        placehold: "請選擇參與狀態",
        select: ["已參與", "未參與", "待參與"],
      },
      missclassRecord: {
        placehold: "請選擇補課狀態",
        select: ["無補課", "已補課", "未補課"],
      },
      callManagement: {
        addCall: "添加電訪",
        callRecord: "電訪記錄",
        name: "姓名",
        count: "已溝通次數",
        time: "上次溝通時間",
        tim: "溝通時間",
        none: "不限",
        mode: "查看溝通模版",
        form: {
          commun_type: "溝通類型",
          commun_type_ph: "請選擇溝通類型",
          commun_name: "溝通對象",
          commun_name_ph: "請選擇溝通對象",
          commun_time: "溝通日期",
          commun_time_ph: "請選擇溝通日期",
          commun_result: "溝通結果",
          commun_result_ph: "請選擇溝通結果",
          commun_result_arr: ["無效溝通", "有效溝通"],
          commun_content: "溝通內容",
          commun_content_ph: "請輸入溝通內容",
          commun_nexttime: "下次跟進日期",
          commun_nexttime_ph: "請選擇下次跟進日期",
          red_tip: "*為必填字段",
        },
        call_time: "電訪日期",
        range: "至",
        start_time: "開始日期",
        end_time: "結束日期",
        find_ph: "請輸入姓名/學號",
        find_ph1: "請輸入學員中文名、英文名、學員編號",
        a1: "查看電訪",
        a2: "學員中文名",
        a3: "學員英文名",
        a4: "學員編號",
        a5: "本次電訪狀態",
        a6: "上次電訪時間",
        a7: "添加電訪記錄",
        a8: "查看電訪記錄",
        a9: "查看本次電訪話術",
        a10: "電訪狀態",
        a11: "請選擇電訪狀態",
      },
      a1: "一鍵已參與",
      a2: "一鍵無補課",
      a3: "一鍵已完成",
    },
    // 教務檢核狀況
    checkStatusrouter: {
      title: "教務核檢狀況",
      handsee: "查看",
      viewCheckStatus: "查看核檢狀況",
      viewCheckDetails: "查看教務核檢詳情",
      classTeaching: {
        online: "線上",
        offline: "線下",
        homework_finish: "作業完成率",
        record_course: "錄播課程",
        course_watch: "錄播課程觀看狀況 (次數)",
        online_score: "線上檢測分數",
        dub_rate: "配音達標率",
        teacher_word: "老師評語",
        parent_word: "家長反饋",
        parent_servey: "家長滿意度調查函",
        parent_inquiry: "家長滿意度調查",
        offline_test: "線下考試成績",
        offline_homework: "線下作業分數",
        book_check: "小書檢核",
        course_take: "網課參與",
        course_score: "網課檢測分數",
        lesson_record: "補課記錄",
        ci: "次",
      },
    },
    // 報表
    educationalReport: {
      title1: "班級教師統計報表",
      title2: "中心基地報表",
      title3: "教務工作報表",
      classReport: {
        campus: "校園",
        campus_ph: "請選擇校園",
        class: "課程別",
        class_ph: "請選擇課程別",
        find_ph: "請輸入班級名稱/班級編號",
        find_ph1: "請輸入班級中英文名、班級編號",
        classTime: "課時統計",
        callRecord: "電訪記錄",
        findDetail: "查看明細",
      },
      teacherReport: {
        campus: "校園",
        campus_ph: "請選擇校園",
        find_ph: "請輸入教師名稱/教師編號",
        roomCount: "班級統計",
      },
      schoolTaskReport: {
        a1: "選擇時間",
        a2: "組織架構模式",
        a3: "請選擇組織架構模式",
        a4: "組織架構",
        a5: "二級架構",
        a6: "三級架構",
        a7: "查看校總表",
        a8: "校總表",
        find_ph: "請輸入學校名稱搜索",
      },
      classTaskReport: {
        find_ph: "請輸入班級中英文名",
      },
      classTime: {
        class_name: "班級名稱",
        school_name: "校園名稱",
        class_progress: "課時進度",
        class_info: "課時信息",
        class: "課時",
        class_ph: "請選擇課時",
        student_info: "學生檢核狀況",
        find_ph: "請輸入學員中英文姓名/學員編號",
      },
      callRecord: {
        student_list: "學生列表",
        call_time: "電訪日期",
        range: "至",
        start_time: "開始日期",
        end_time: "結束日期",
        find_ph: "請輸入學員中英文姓名/學員編號",
      },
      eduWorkDetail: {
        a1: "班級中文名",
        a2: "班級英文名",
        a3: "班級編號",
        a4: "主教老師",
        a5: "助教老師",
        a6: "應上/總課次數",
        a7: "實際登記課次數",
        a8: "未登記課次數",
        a9: "上課狀態",
        a10: "請選擇上課狀態",
        a11: "登記狀態",
        a12: "請選擇登記狀態",
        a13: "請輸入課次名稱",
        a14: ["已考勤", "待考勤", "待上課"],
        a15: ["已登記", "未登記"],
      },
    },
    // 課表
    MySchedule: {
      page_title: "我的課表",
    },
    // 叮鐺助教
    JingleAssistant: {
      timeListText: [
        "不限",
        "今日",
        "昨日",
        "本周",
        "近7天",
        "近30天",
        "本月",
        "上月",
      ],
      // 教務工作
      educationWork: {
        page_title: "教務工作",
        innerSliderArr: ["上課點評", "發布作業", "溝通管理", "通知管理"],
        labe1: "班",
        labe2: "課程別名稱",
        labe3: "課程別編號",
        labe4: "校園",
        labe5: "教師",
        labe6: "教室",
        labe7: "人數",
        // 上課點評
        child1: {
          labe1: "請選擇課時",
          labe2: "上課內容",
          labe3: "添加上課內容",
          labe4: "點評狀態：",
          labe5: "已選中",
          labe6: "個學員",
          btn_text1: "查看",
          btn_text2: "重新編輯",
          btn_text3: "點評",
          btn_text4: "撤銷點評",
          btn_text5: "清空",
          btn_text6: "保存草稿",
          btn_text7: "提交",
          btn_text8: "上傳圖片",
          btn_text9: "選擇評價模版",
          labe7: "已選擇",
          labe10: "人",
          placeholder1: "請輸入上課內容",
          placeholder2: "請輸入對學生的評價",
          title1: "批量點評",
          title2: "點評",
          title3: "查看點評",
          title4: "編輯點評",
          title5: "選擇點評模板",
          labe8: "共",
          labe9: "條評價",
          TabList: ["全部", "已評", "未評"],
          popTipsRevoke: "撤銷點評後，家長將不收到此點評內容，確定撤銷點評？",
          imgTips1: "上傳頭像圖片只能是 JPG/PNG/GIF 格式!",
          imgTips2: "上傳頭像圖片大小不能超過 2MB!",
        },
        // 發布作業
        child2: {
          aa: "發布作業",
          ab: "已發布作業",
          ac: "作業已發布成功",
          ad: "繼續發布",
          ae: "清空",
          af: "發送",
          ag: "請選擇課時",
          ah: "接收人",
          ai: "接收人數",
          aj: "添加學生",
          ak: "標題",
          al: "請輸入標題",
          am: "內容",
          an: "共",
          ao: "人未添加",
          ap: "請輸入作業標題",
          aq: "請輸入作業內容",
          ar: "查看",
          as: "待上課的課時暫時不能發布作業哦~ ",
        },
        // 溝通管理
        child3: {
          aa: "請輸入姓名、編號",
          ab: "添加溝通",
          ac: "溝通記錄",
          ad: "選擇溝通模版",
        },
        // 通知管理
        child4: {
          aa: "發布通知",
          ab: "通知列表",
          ac: "通知發布成功",
          ad: "請輸入通知標題",
          ae: "請輸入通知內容",
          af: "發布時間",
          ag: "請選擇時間範圍",
          ah: "查看",
          ai: "查看閱讀狀態",
        },
      },
      // 作業管理
      homeWork: {
        page_title: "作業管理",
        innerSliderArr: ["作業查詢", "作業統計"],
        labe_text1: "時間範圍",
        placeholder1: "請選擇時間範圍",
        labe_text11: "學校",
        placeholder11: "請選擇學校",
        labe_text2: "班級",
        placeholder2: "請選擇班級",
        labe_text3: "老師",
        placeholder3: "請選擇老師",
        placeholder4: "標題",
        labe_text4: "發送人：",
        labe_text5: "上課時間：",
        labe_text6: "接收人",
        labe_text7: "閱讀狀態",
        placeholder5: "請選擇時間範圍",
        placeholder6: "班級名稱",
        placeholder7: "老師名稱",
        title1: "作業詳情",
        title2: "查看作業完成狀態",
        tips:
          "1、作業數表示發布作業數量；2、發送人數表示已發送作業的學員數量；3、閱讀人數表示已閱讀作業的學員數量；4、提交人數表示已提交的學員數量；5、評價人數表示老師評價的學員數量",
        tabs: ["已讀", "未讀", "已交", "已評", "全部"],
        pageTabs: ["按班級", "按老師"],
        blankTips: [
          "暫無已讀作業",
          "暫無未讀作業",
          "暫無已交作業",
          "暫無已評作業",
          "暫無全部作業",
        ],
      },
      // 通知管理
      noticeManage: {
        page_title: "通知管理",
        innerSliderArr: ["通知管理", "公告管理"],
        labe_text1: "時間範圍",
        placeholder1: "請選擇時間範圍",
        labe_text2: "班級",
        placeholder2: "請選擇班級",
        labe_text3: "老師",
        placeholder3: "請選擇老師",
        placeholder4: "標題",
        labe_text4: "發送人：",
        labe_text5: "已讀人數：",
        title1: "通知詳情",
        title2: "查看通知完成狀態",
        title3: "公告詳情",
        title4: "發布通告",
        title5: "編輯公告",
        btn_text1: "發布公告",
        btn_text2: "發布",
        btn_text3: "編輯",
        tips: "接收人為我校學員",
        tabs: ["已讀", "未讀", "全部"],
        status: ["已讀", "未讀"],
        form_text1: "公告標題：",
        form_text100: "所屬學校：",
        form_text2: "公告內容：",
        form_rule1: "請輸入公告標題",
        form_rule2: "請輸入公告內容",
        blankTips: ["暫無已讀通知", "暫無未讀通知", "暫無全部通知"],
      },
      // 家長評價老師
      parentAssess: {
        aa: "按老師",
        ab: "按老師+班級",
        ac: "家長評價老師",
        ad: "評價查詢",
        ae: "老師得分統計",
        af: "時間範圍",
        ag: "選擇時間",
        ah: "選擇日期",
        ai: "班級",
        aj: "選擇班級",
        ak: "老師",
        al: "選擇老師",
        am: "學員中英文名、學員編號、聯系電話",
        an: "出勤學員評價詳情",
        ao: "是否評價",
        ap: "請輸入學員中英文名、學員編號",
        aq: "否",
        ar: "是",
      },
      // 投訴與建議
      complaint: {
        page_title: "投訴與建議",
        innerSliderArr: ["學校", "老師"],
        labe_text1: "時間範圍",
        placeholder1: "請選擇時間範圍",
        labe_text2: "選擇日期",
        placeholder2: "學員中英文名、學員編號、聯系電話",
        title1: "投訴與建議",
        labe_text3: "時間",
        labe_text4: "對象",
      },
    },
  },
  // 個人中心
  myCenter: {
    page_myClass_title: "我的班級",
    page_currentCourse_title: "在學課程",
    page_myComment_title: "我的批註",
    page_myCollect_title: "我的收藏",
    page_myVideo_title: "我的教學視頻",
    page_myNote_title: "我的筆記",
    video_mark: "優秀教學視頻",
    placeholder1: "請輸入班級名稱、課程別名稱、課程別編號",
    placeholder2: "請輸入課程名稱",
    placeholder3: "請輸入課時名稱",
    placeholder4: "請選擇審核類型",
    placeholder5: "請輸入內容",
    tips_title: " 溫馨提示：",
    tips_cont1:
      "上傳您的教學視頻後將由學校審核，學校審核通過後將有機會將您的教學視頻推薦為優秀教學視頻供老師們查看哦～",
    tips_cont2: "審核拒絕後您可重新上傳 新的教學視頻～",
    labe_text1: "進行中",
    labe_text2: "未開始",
    labe_text3: "課程別：",
    labe_text4: "課程別編號：",
    labe_text5: "校園：",
    labe_text6: "人數：",
    labe_text7: "完成度",
    labe_text8: "審核類型",
    labe_text9: "上傳日期：",
    labe_text10: "人已學",
    video_status: ["待審核", "審核通過", "審核駁回"],
  },
  // 消息中心
  myMessage: {
    btn_text1: "標記已讀",
    page_messageDetail_title: "消息詳情",
  },
  // 個人設置
  mySettings: {
    page_myinfo_title: "個人信息",
    page_accoutInfo_title: "賬號信息",
    page_common_title: "基本信息",
    page_staff_title: "職務信息",
    head_photo: "頭像",
    img_text: [
      "將圖片拖到此處，或",
      "點擊上傳",
      "僅限jpeg，png格式，圖片大小不超過2M",
    ],
    page_info: {
      teacher_cname: "教師中文名",
      teacher_ename: "教師英文名",
      gender: "性別",
      man: "男",
      women: "女",
      date: "出生日期",
      staff_name: "職務名稱",
      job: "角色",
      staff_leavel: "職等",
      account: "賬號",
      password: "修改密碼",
      number: "手機號",
      email: "郵箱",
      changepassword: "修改密碼",
    },
    password_dialog: {
      titie: "修改密碼",
      newpass: "請輸入新密碼",
      newpass_ph: "請輸入六位數字新密碼",
      confirmpass: "請確認密碼",
      confirmpass_ph: "請再次確認密碼",
      confirm: "確認",
      cancel: "取消",
    },
  },
  // 公共部分
  Common: {
    header: {
      nav_name1: "趣備課",
      nav_name2: "培訓",
      nav_name3: "教務管理",
      languageTab: "切換語言",
      userOperate1: "個人中心",
      userOperate2: "個人設置",
      userOperate3: "退出登錄",
      changeSchoolTitle: "請選擇您要進入的學校",
      schoolTab: "切換",
      changeSchool: {
        placeholder1: "選擇區域",
        placeholder2: "選擇省",
        placeholder3: "選擇市",
        placeholder4: "請輸入校園編號,校園名稱",
      },
    },
    mode: {
      card_mode: "卡片模式",
      list_mode: "列表模式",
    },
    collect_text: "收藏",
    video_tips: "您的瀏覽器不支持 video 標簽",
    page: ["第", "頁"],
    pop_title: "提示",
    noread_text: "未讀",
    btn_save: "保存",
    btn_edit: "修改",
    btn_del: "刪除",
    btn_edit2: "編輯",
    btn_sure: "確定",
    btn_cancel: "取消",
    log_out_cont: "確定退出當前帳號？",
    input_button: "查詢",
    input_submit: "提交",
    btn_see_comment: "查看批註",
    export: "導出",
    export_tips: "沒有可導出的數據哦",
    print: "打印",
    preview: "預覽",
    see: "查看",
    piece: "個",
    download: "下載",
    start_time: "開始日期",
    end_time: "結束日期",
    range_time: "至",
    man: "男",
    woman: "女",
    popTips: "提示",
    popTips_del: "是否確定刪除？",
    table_operate: "操作",
    audioTips: "您的瀏覽器不支持 audio 標簽。",
    videoTips: "您的瀏覽器不支持 video 標簽。",
    back: "返回",
  },
  // 組件-----------start
  // 表格
  Table: {
    a1: "啊哦～暫時沒有內容哦",
    a2: "編輯列",
    a3: "已顯示列",
    a4: "未顯示列",
    a5: "確定",
    a6: "提示",
  },
  // 課表
  mySchedule: {
    tabsList: ["日視圖", "周視圖", "月視圖"],
    statusArr: ["待考勤", "已考勤"],
    placeholder1: "選擇日期",
    placeholder2: "選擇月",
    text: "至",
    labe_text1: "時間：",
    labe_text2: "班級別名：",
    labe_text3: "課程別：",
    labe_text4: "校區：",
    labe_text5: " 教室：",
    labe_text6: "狀態：",
    emptyTip: "課表暫無數據",
    weekdayArr: ["周日", "周一", "周二", "周三", "周四", "周五", "周六"],
  },
  // 組件-----------end
  // 路由部分
  storeRouter: {
    Slider1: ["首頁", "備課", "報表"],
    Slider2: ["職業成長", "通識課", "報表"],
    Slider3: [
      "首頁",
      "我的課表",
      "小循環登記",
      "教務檢核狀況",
      "叮鐺助教",
      "教務工作",
      "消息查詢",
      "作業管理",
      "通知管理",
      "老師評價學生",
      "家長評價老師",
      "投訴與建議",
      "報表",
    ],
    Slider4: [
      "我的班級",
      "在學課程",
      "我的批註",
      "我的筆記",
      "我的教學視頻",
      "我的收藏",
    ],
    Slider5: ["個人信息", "賬號信息"],
  },
};
